movie_clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      schema: gold
      host: clickhouse-server
      port: 8123              # Native protocol port
      user: dbt_user
      password: dbt_password
      secure: false
      verify: false
      driver: http
      connect_timeout: 10
      send_receive_timeout: 300