movie_clickhouse:
  target: dev
  outputs:
    dev:
      type: clickhouse
      host: clickhouse-server
      port: 8123
      user: dbt_user
      password: dbt_password
      schema: "{{ env_var('DBT_SCHEMA', 'gold') }}"
      driver: http
      secure: false
      verify: false
      connect_timeout: 10
      send_receive_timeout: 300
